openapi: 3.2.0
info:
  title: BloodHound Risk Posture API
  contact:
    name: BloodHound Enterprise Support
    url: https://bloodhound.specterops.io/
    email: support@specterops.io
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v2
  description: This is the API that drives BloodHound Enterprise and Community Edition.
servers:
- url: /
  description: This is the base path for all endpoints, relative to the domain where the API is being hosted.
security:
- JWTBearerToken: []
- SignedRequest: []
  RequestDate: []
  HMACSignature: []
tags:
- name: Risk Posture
paths:
  /api/v2/posture-stats:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetPostureStats
      summary: Get Posture Statistics
      description: Gets the history of database stats saved in the database
      tags:
      - Risk Posture
      parameters:
      - name: sort_by
        description: Sortable columns are `domain_sid`, `exposure_index`, `tier_zero_count`, `critical_risk_count`, `id`, `created_at`, `updated_at`, `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - name: from
        deprecated: true
        x-go-name: fromDeprecated
        description: Lower bound for created_at; to return posture stats starting at a specific date/time. This filter has been deprecated, please use created_at instead.
        in: query
        schema:
          type: string
          format: date-time
      - name: to
        deprecated: true
        x-go-name: toDeprecated
        description: Upper bound for created_at; to return posture stats upto a specific date/time. This filter has been deprecated, please use created_at instead.
        in: query
        schema:
          type: string
          format: date-time
      - name: domain_sid
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.string'
      - name: exposure_index
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.integer'
      - name: asset_group_tag_id
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.integer'
      - name: tier_zero_count
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.integer'
      - name: critical_risk_count
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.integer'
      - name: id
        in: query
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.integer'
      - name: created_at
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.time'
      - name: updated_at
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.time'
      - name: deleted_at
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/api.params.predicate.filter.time'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/api.response.pagination'
                - $ref: '#/components/schemas/api.response.time-window'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/model.risk-posture-stat'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/posture-history/{data_type}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: data_type
      description: The type of posture data to return
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/enum.posture-history-type'
    - $ref: '#/components/parameters/query.asset-group-tag-id'
    get:
      operationId: PostureHistoryForEnvironments
      summary: Get Posture History
      description: Gets posture data count changes over a time period
      tags:
      - Risk Posture
      parameters:
      - name: environments
        description: Environment IDs
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      - name: start
        description: Beginning datetime of range (inclusive) in RFC-3339 format; Defaults to current datetime minus 30 days
        in: query
        schema:
          type: string
          format: date-time
      - name: end
        description: Ending datetime of range (exclusive) in RFC-3339 format; Defaults to current datetime
        in: query
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/api.response.time-window'
                - type: object
                  properties:
                    environments:
                      type: array
                      items:
                        type: string
                    data_type:
                      $ref: '#/components/schemas/enum.posture-history-type'
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          date:
                            type: string
                            format: date-time
                            readOnly: true
                          value:
                            type: number
                            format: double
                            readOnly: true
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
components:
  responses:
    forbidden:
      description: '**Forbidden**

        This is most commonly caused by an authenticated client trying to

        access a resource that it does not have permission for.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 403
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: You do not have permission to access this resource
    internal-server-error:
      description: '**Internal Server Error**

        This is usually the result of either an unexpected database or application error.

        The client may try modifying or resending the request, but the error is likely not related to the client

        doing something wrong.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 500
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The request could not be handled due to an unexpected database error.
    unauthorized:
      description: '**Unauthorized**

        This endpoint failed an authentication requirement. Either the client tried to access

        a protected endpoint without being authenticated, or an auth validation failed (ex- invalid

        credentials or expired token).

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 401
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: login
              message: Unauthorized
    too-many-requests:
      description: '**Too Many Requests**

        The client has sent too many requests within a certain time window

        and tripped the rate limiting middleware.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 429
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: middleware
              message: Too many requests. Please try again later.
    not-found:
      description: '**Not Found**

        This error typically comes from operations where a valid ID was passed to the request

        to look up an entity but the entity could not be found.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 404
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The requested client could not be found.
    bad-request:
      description: '**Bad Request**

        This could be due to one of the following reasons:

        - JSON payload is missing or malformed

        - Path or query parameters are missing or invalid/malformed

        - The data sent is not valid (ex- sending a `string` in an `integer` field)

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 400
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The JSON payload could not be unmarshalled.
  schemas:
    api.params.query.limit:
      type: integer
      minimum: 0
      description: The limit of results requested by the client.
    api.params.predicate.filter.integer:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?-?[0-9]+$
      description: 'Filter results by column integer value. Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    model.risk-posture-stat:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - $ref: '#/components/schemas/model.components.timestamps'
      - type: object
        properties:
          domain_sid:
            type: string
          exposure_index:
            type: number
            format: double
          tier_zero_count:
            type: integer
            format: int64
          critical_risk_count:
            type: integer
    enum.posture-history-type:
      type: string
      description: This enum describes the valid data types for posture history results.
      enum:
      - findings
      - exposure
      - assets
      - session-completeness
      - group-completeness
      - attack-paths
      - archived-findings
    null.time:
      type: object
      properties:
        time:
          type: string
          format: date-time
          description: An RFC-3339 formatted string
        valid:
          description: Valid is true if `time` is not `null`.
          type: boolean
    api.error-detail:
      type: object
      properties:
        context:
          type: string
          description: The context in which the error took place
        message:
          type: string
          description: A human-readable description of the error
    api.params.query.sort-by:
      type: string
      description: 'Sort by column. Can be used multiple times; prepend a hyphen for descending order.

        See parameter description for details about which columns are sortable.

        '
    model.components.timestamps:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/null.time'
    model.components.int64.id:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: This is the unique identifier for this object.
    api.params.predicate.filter.string:
      type: string
      pattern: ^((eq|~eq|neq):)?[^:]+$
      description: 'Filter results by column string value. Valid filter predicates are `eq`, `~eq`, `neq`.

        '
    api.params.predicate.filter.time:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?[0-9]{4}-[0-9]{2}-[0-9]{2}[Tt][0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,9})?([Zz]|-[0-9]{2}:[0-9]{2})$
      description: 'Filter results by column timestamp value formatted as an RFC-3339 string.

        Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    api.response.time-window:
      type: object
      properties:
        start:
          type: string
          format: date-time
          description: The RFC-3339 timestamp to describe the beginning of a time range
        end:
          type: string
          format: date-time
          description: The RFC-3339 timestamp to describe the end of a time range
    api.response.pagination:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          description: The total number of results.
        skip:
          $ref: '#/components/schemas/api.params.query.skip'
        limit:
          $ref: '#/components/schemas/api.params.query.limit'
    api.params.query.skip:
      type: integer
      minimum: 0
      description: The number of items to skip in a paginated response.
    api.error-wrapper:
      type: object
      description: ''
      properties:
        http_status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 600
        timestamp:
          type: string
          format: date-time
          description: The RFC-3339 timestamp in which the error response was sent
        request_id:
          type: string
          format: uuid
          description: The unique identifier of the request that failed
        errors:
          type: array
          items:
            $ref: '#/components/schemas/api.error-detail'
          description: The error(s) that occurred from processing the request
  parameters:
    query.asset-group-tag-id:
      name: asset_group_tag_id
      description: The asset group tag id of the zone requested. If not supplied, the asset group tag id associated with 'Tier Zero' and 'Hygiene' is used.
      in: query
      schema:
        type: integer
    header.prefer:
      name: Prefer
      description: Prefer header, used to specify a custom timeout in seconds using the wait parameter as per RFC7240. Passing in wait=-1 bypasses all timeout limits when the feature is enabled.
      in: header
      required: false
      schema:
        type: string
        default: wait=30
        pattern: ^wait=(-1|[0-9]+)$
  securitySchemes:
    JWTBearerToken:
      description: '`Authorization: Bearer $JWT_TOKEN`

        '
      type: http
      scheme: bearer
      bearerFormat: JWT
    SignedRequest:
      description: '`Authorization: bhesignature $TOKEN_ID`

        '
      type: apiKey
      name: Authorization
      in: header
    RequestDate:
      description: '`RequestDate: $RFC3339_DATETIME`

        '
      type: apiKey
      name: RequestDate
      in: header
    HMACSignature:
      description: '`Signature: $BASE64ENCODED_HMAC_SIGNATURE`

        '
      type: apiKey
      name: Signature
      in: header
x-tagGroups:
- name: Community & Enterprise
  tags:
  - Auth
  - Roles
  - Permissions
  - API Tokens
  - BloodHound Users
  - Collectors
  - Collection Uploads
  - Custom Node Management
  - API Info
  - Search
  - Audit
  - Config
  - Asset Isolation
  - Graph
  - Azure Entities
  - AD Base Entities
  - Computers
  - Containers
  - Domains
  - GPOs
  - AIA CAs
  - Root CAs
  - Enterprise CAs
  - NT Auth Stores
  - Cert Templates
  - OUs
  - AD Users
  - Groups
  - Data Quality
  - Datapipe
  - Cypher
  - OpenGraph (Experimental)
- name: Enterprise Only
  tags:
  - EULA
  - BHE Users
  - Analysis
  - Client Ingest
  - Clients
  - Jobs
  - Tasks
  - Events (Schedules)
  - Attack Paths
  - Risk Posture
  - Meta Entities
  - Alerts
