openapi: 3.2.0
info:
  title: BloodHound Collectors API
  contact:
    name: BloodHound Enterprise Support
    url: https://bloodhound.specterops.io/
    email: support@specterops.io
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v2
  description: This is the API that drives BloodHound Enterprise and Community Edition.
servers:
- url: /
  description: This is the base path for all endpoints, relative to the domain where the API is being hosted.
security:
- JWTBearerToken: []
- SignedRequest: []
  RequestDate: []
  HMACSignature: []
tags:
- name: Collectors
paths:
  /api/v2/collectors/{collector_type}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: collector_type
      description: Collector type
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/enum.client-type'
    get:
      operationId: GetCollectorManifest
      summary: Get collector manifest
      description: Retrieves the version manifest for a given collector
      tags:
      - Collectors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.collector-manifest'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/collectors/{collector_type}/{release_tag}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: collector_type
      description: Collector type
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/enum.client-type'
    - name: release_tag
      description: Release tag (semver or "latest")
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: DownloadCollector
      summary: Get collector download by version
      description: Retrieves the download for a given collector with given version
      tags:
      - Collectors
      responses:
        '200':
          $ref: '#/components/responses/binary-response'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/collectors/{collector_type}/{release_tag}/checksum:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: collector_type
      description: Collector type
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/enum.client-type'
    - name: release_tag
      description: Release tag (semver or "latest")
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: GetCollectorChecksum
      summary: Get collector checksum by version
      description: Retrieves the checksum file for a given collector with given version
      tags:
      - Collectors
      responses:
        '200':
          $ref: '#/components/responses/binary-response'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/kennel/manifest:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetKennelManifest
      summary: Get kennel manifest
      description: Retrieves a manifest of community collectors
      tags:
      - Collectors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.kennel-manifest'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/kennel/enterprise-manifest:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetKennelEnterpriseManifest
      summary: Get kennel enterprise manifest
      description: Retrieves a manifest of enterprise collectors
      tags:
      - Collectors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.kennel-enterprise-manifest'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/kennel/download/{asset_name}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: asset_name
      description: Asset name
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: GetKennelAsset
      summary: Download asset
      description: Downloads an enterprise asset (collector or checksum)
      tags:
      - Collectors
      responses:
        '200':
          $ref: '#/components/responses/binary-response'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
components:
  schemas:
    model.kennel-manifest:
      type: object
      properties:
        sharphound:
          type: array
          items:
            $ref: '#/components/schemas/model.kennel-version'
        azurehound:
          type: array
          items:
            $ref: '#/components/schemas/model.kennel-version'
    model.collector-version:
      type: object
      properties:
        version:
          type: string
        sha256sum:
          type: string
        deprecated:
          type: boolean
    api.error-detail:
      type: object
      properties:
        context:
          type: string
          description: The context in which the error took place
        message:
          type: string
          description: A human-readable description of the error
    model.kennel-asset:
      type: object
      properties:
        name:
          type: string
        download_url:
          type: string
        checksum_download_url:
          type: string
        os:
          type: string
        arch:
          type: string
    enum.client-type:
      type: string
      description: This enum describes the collector client type.
      enum:
      - sharphound
      - azurehound
      - openhound
    model.kennel-enterprise-manifest:
      type: object
      properties:
        sharphound_enterprise:
          type: array
          items:
            $ref: '#/components/schemas/model.kennel-version'
        azurehound_enterprise:
          type: array
          items:
            $ref: '#/components/schemas/model.kennel-version'
    model.kennel-version:
      type: object
      properties:
        version:
          type: string
        version_meta:
          $ref: '#/components/schemas/model.version-meta'
        release_date:
          type: string
          format: date-time
        release_assets:
          type: array
          items:
            $ref: '#/components/schemas/model.kennel-asset'
    api.error-wrapper:
      type: object
      description: ''
      properties:
        http_status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 600
        timestamp:
          type: string
          format: date-time
          description: The RFC-3339 timestamp in which the error response was sent
        request_id:
          type: string
          format: uuid
          description: The unique identifier of the request that failed
        errors:
          type: array
          items:
            $ref: '#/components/schemas/api.error-detail'
          description: The error(s) that occurred from processing the request
    model.collector-manifest:
      type: object
      properties:
        latest:
          type: string
        versions:
          type: array
          items:
            $ref: '#/components/schemas/model.collector-version'
    model.version-meta:
      type: object
      properties:
        major:
          type: integer
        minor:
          type: integer
        patch:
          type: integer
        prerelease:
          type: string
  responses:
    internal-server-error:
      description: '**Internal Server Error**

        This is usually the result of either an unexpected database or application error.

        The client may try modifying or resending the request, but the error is likely not related to the client

        doing something wrong.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 500
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The request could not be handled due to an unexpected database error.
    unauthorized:
      description: '**Unauthorized**

        This endpoint failed an authentication requirement. Either the client tried to access

        a protected endpoint without being authenticated, or an auth validation failed (ex- invalid

        credentials or expired token).

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 401
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: login
              message: Unauthorized
    not-found:
      description: '**Not Found**

        This error typically comes from operations where a valid ID was passed to the request

        to look up an entity but the entity could not be found.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 404
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The requested client could not be found.
    bad-request:
      description: '**Bad Request**

        This could be due to one of the following reasons:

        - JSON payload is missing or malformed

        - Path or query parameters are missing or invalid/malformed

        - The data sent is not valid (ex- sending a `string` in an `integer` field)

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 400
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The JSON payload could not be unmarshalled.
    binary-response:
      description: '**OK**

        This response will contain binary content.

        '
      headers:
        Content-Disposition:
          schema:
            type: string
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
          example: '[this request has a binary response]'
  parameters:
    header.prefer:
      name: Prefer
      description: Prefer header, used to specify a custom timeout in seconds using the wait parameter as per RFC7240. Passing in wait=-1 bypasses all timeout limits when the feature is enabled.
      in: header
      required: false
      schema:
        type: string
        default: wait=30
        pattern: ^wait=(-1|[0-9]+)$
  securitySchemes:
    JWTBearerToken:
      description: '`Authorization: Bearer $JWT_TOKEN`

        '
      type: http
      scheme: bearer
      bearerFormat: JWT
    SignedRequest:
      description: '`Authorization: bhesignature $TOKEN_ID`

        '
      type: apiKey
      name: Authorization
      in: header
    RequestDate:
      description: '`RequestDate: $RFC3339_DATETIME`

        '
      type: apiKey
      name: RequestDate
      in: header
    HMACSignature:
      description: '`Signature: $BASE64ENCODED_HMAC_SIGNATURE`

        '
      type: apiKey
      name: Signature
      in: header
x-tagGroups:
- name: Community & Enterprise
  tags:
  - Auth
  - Roles
  - Permissions
  - API Tokens
  - BloodHound Users
  - Collectors
  - Collection Uploads
  - Custom Node Management
  - API Info
  - Search
  - Audit
  - Config
  - Asset Isolation
  - Graph
  - Azure Entities
  - AD Base Entities
  - Computers
  - Containers
  - Domains
  - GPOs
  - AIA CAs
  - Root CAs
  - Enterprise CAs
  - NT Auth Stores
  - Cert Templates
  - OUs
  - AD Users
  - Groups
  - Data Quality
  - Datapipe
  - Cypher
  - OpenGraph (Experimental)
- name: Enterprise Only
  tags:
  - EULA
  - BHE Users
  - Analysis
  - Client Ingest
  - Clients
  - Jobs
  - Tasks
  - Events (Schedules)
  - Attack Paths
  - Risk Posture
  - Meta Entities
  - Alerts
