openapi: 3.0.3
info:
  title: BloodHound AD Base Entities Tasks API
  contact:
    name: BloodHound Enterprise Support
    url: https://bloodhound.specterops.io/
    email: support@specterops.io
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v2
  description: "This is the API that drives BloodHound Enterprise and Community Edition.\nEndpoint availability is denoted using the `Community` and `Enterprise` tags.\n\nContact information listed is for BloodHound Enterprise customers. To get help with\nBloodHound Community Edition, please join our\n[Slack community](https://ghst.ly/BHSlack/).\n\n## Authentication\n\nThe BloodHound API supports two kinds of authentication: JWT bearer tokens and Signed Requests.\nFor quick tests or one-time calls, the JWT used by your browser may be the simplest route. For\nmore secure and long lived API integrations, the recommended option is signed requests.\n\n### JWT Bearer Token\n\nThe API will accept calls using the following header structure in the HTTP request:\n```\nAuthorization: Bearer $JWT_TOKEN\n```\nIf you open the Network tab within your browser, you will see calls against the API made utilizing\nthis structure. JWT bearer tokens are supported by the BloodHound API, however it is recommended\nthey only be used for temporary access. JWT tokens expire after a set amount of time and require\nre-authentication using secret credentials.\n\n### Signed Requests\n\nSigned requests are the recommended form of authentication for the BloodHound API. Not only are\nsigned requests better for long lived integrations, they also provide more security for the\nrequests being sent. They provide authentication of the client, as well as verification of request\nintegrity when received by the server.\n\nSigned requests consist of three main parts: The client token ID, the request timestamp, and a\nbase64 encoded HMAC signature. These three pieces of information are sent with the request using\nthe following header structure:\n\n```\nAuthorization: bhesignature $TOKEN_ID\nRequestDate: $RFC3339_DATETIME\nSignature: $BASE64ENCODED_HMAC_SIGNATURE\n```\n\nTo use signed requests, you will need to generate an API token. Each API token generated in the\nBloodHound API comes with two parts: The Token ID, which is used in the `Authorization` header,\nand the Token Key, which is used as part of the HMAC hashing process. The token ID should be\nconsidered as public (like a username) and the token key should be considered secret (like a\npassword). Once an API token is generated, you can use the key to sign requests.\n\nFor more documentation about how to work with authentication in the API, including examples\nof how to generate an API token in the BloodHound UI, please refer to this support doc:\n[Working with the BloodHound API](https://bloodhound.specterops.io/integrations/bloodhound-api/working-with-api).\n\n#### Signed Request Pseudo-code Example\n\nFirst, a digest is initiated with HMAC-SHA-256 using the token key as the digest key:\n```python\ndigester = hmac.new(sha256, api_token_key)\n```\n\nOperationKey is the first HMAC digest link in the signature chain. This prevents replay attacks that\nseek to modify the request method or URI. It is composed of concatenating the request method and\nthe request URI with no delimiter and computing the HMAC digest using the token key as the digest\nsecret:\n```python\n# Example: GET /api/v2/test/resource HTTP/1.1\n# Signature Component: GET/api/v2/test/resource\ndigester.write(request_method + request_uri)\n\n# Update the digester for further chaining\ndigester = hmac.New(sha256, digester.hash())\n```\n\nDateKey is the next HMAC digest link in the signature chain. This encodes the RFC3339\nformatted datetime value as part of the signature to the hour to prevent replay\nattacks that are older than max two hours. This value is added to the signature chain\nby cutting off all values from the RFC3339 formatted datetime from the hours value\nforward:\n```python\n# Example: 2020-12-01T23:59:60Z\n# Signature Component: 2020-12-01T23\nrequest_datetime = date.now()\ndigester.write(request_datetime[:13])\n\n# Update the digester for further chaining\ndigester = hmac.New(sha256, digester.hash())\n```\n\nBody signing is the last HMAC digest link in the signature chain. This encodes the\nrequest body as part of the signature to prevent replay attacks that seek to modify\nthe payload of a signed request. In the case where there is no body content the\nHMAC digest is computed anyway, simply with no values written to the digester:\n```python\nif request.body is not empty:\n  digester.write(request.body)\n```\n\nFinally, base64 encode the final hash and write the three required headers before\nsending the request:\n```python\nencoded_hash = base64_encode(digester.hash())\nrequest.header.write('Authorization', 'bhesignature ' + token_id)\nrequest.header.write('RequestDate', request_datetime)\nrequest.header.write('Signature', encoded_hash)\n```\n"
servers:
- url: /
  description: This is the base path for all endpoints, relative to the domain where the API is being hosted.
security:
- JWTBearerToken: []
- SignedRequest: []
  RequestDate: []
  HMACSignature: []
tags:
- name: Tasks
paths:
  /api/v2/tasks/available:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: ListAvailableClientTasks
      deprecated: true
      summary: List available client tasks
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs/available` instead.

        '
      tags:
      - Tasks
      parameters:
      - name: sort_by
        description: Sortable columns are `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, and `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.clients.hydrate-ous'
      - $ref: '#/components/parameters/query.clients.hydrate-domains'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/finished:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: ListClientFinishedTasks
      deprecated: true
      summary: List finished tasks
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs/finished` instead.

        '
      tags:
      - Tasks
      parameters:
      - name: sort_by
        description: Sortable columns are `client_name`, `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.clients.hydrate-domains'
      - $ref: '#/components/parameters/query.clients.hydrate-ous'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      - $ref: '#/components/parameters/query.skip'
      - $ref: '#/components/parameters/query.limit'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/api.response.pagination'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetClientTasks
      deprecated: true
      summary: Get tasks
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs` instead.

        '
      tags:
      - Tasks
      parameters:
      - name: sort_by
        description: Sortable columns are `client_name`, `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/current:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetClientCurrentTask
      deprecated: true
      summary: Get client current task
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs/current` instead.

        '
      tags:
      - Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/start:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    post:
      operationId: StartClientTask
      deprecated: true
      summary: Notifies the API of a task start
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `POST /api/v2/jobs/start` instead.

        '
      tags:
      - Tasks
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/end:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    post:
      operationId: EndClientTask
      deprecated: true
      summary: Notifies the API of a task ending
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `POST /api/v2/jobs/end` instead.

        '
      tags:
      - Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/{task_id}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: task_id
      description: Task ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    get:
      operationId: GetClientTask
      deprecated: true
      summary: Get client task
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs/{job_id}` instead.

        '
      tags:
      - Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/{task_id}/cancel:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: task_id
      description: Task ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    put:
      operationId: CancelClientTask
      deprecated: true
      summary: Cancels a scheduled task
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `PUT /api/v2/jobs/{job_id}/cancel` instead.

        '
      tags:
      - Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/tasks/{task_id}/log:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: task_id
      description: Task ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    get:
      operationId: GetClientTaskLog
      deprecated: true
      summary: Get Task Log File
      description: '**Deprecated**: This endpoint will no longer be supported in future releases. Please use `GET /api/v2/jobs/{job_id}/log` instead.

        '
      tags:
      - Tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      log:
                        type: string
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
components:
  schemas:
    model.client-scheduled-job:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - $ref: '#/components/schemas/model.components.timestamps'
      - type: object
        properties:
          client_id:
            type: string
            format: uuid
            readOnly: true
          client_name:
            type: string
            readOnly: true
          event_id:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/null.int32'
          status:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/enum.job-status'
          statusMessage:
            type: string
            readOnly: true
          start_time:
            type: string
            format: date-time
            readOnly: true
          end_time:
            type: string
            format: date-time
            readOnly: true
          log_path:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/null.string'
          session_collection:
            type: boolean
          local_group_collection:
            type: boolean
          ad_structure_collection:
            type: boolean
          cert_services_collection:
            type: boolean
          ca_registry_collection:
            type: boolean
          dc_registry_collection:
            type: boolean
          all_trusted_domains:
            type: boolean
          domain_controller:
            $ref: '#/components/schemas/null.string'
          event_title:
            type: string
            readOnly: true
          last_ingest:
            type: string
            format: date-time
            readOnly: true
          ous:
            type: array
            readOnly: true
            items:
              type: string
          domains:
            type: array
            readOnly: true
            items:
              type: string
          domain_results:
            type: array
            readOnly: true
            items:
              $ref: '#/components/schemas/model.domain-collection-result'
    api.response.pagination:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          description: The total number of results.
        skip:
          $ref: '#/components/schemas/api.params.query.skip'
        limit:
          $ref: '#/components/schemas/api.params.query.limit'
    api.params.predicate.filter.boolean:
      type: string
      pattern: ^((eq|neq):)?(t|T|TRUE|true|True|f|F|FALSE|false|False)$
      description: 'Filter results by column boolean value. Valid filter predicates are `eq`, `neq`.

        '
    api.params.predicate.filter.time:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?[0-9]{4}-[0-9]{2}-[0-9]{2}[Tt][0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,9})?([Zz]|-[0-9]{2}:[0-9]{2})$
      description: 'Filter results by column timestamp value formatted as an RFC-3339 string.

        Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    api.params.predicate.filter.integer:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?-?[0-9]+$
      description: 'Filter results by column integer value. Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    enum.job-status:
      type: integer
      description: 'This enum describes the current status of a Job. Values are:

        - `-1` Invalid

        - `0` Ready

        - `1` Running

        - `2` Complete

        - `3` Canceled

        - `4` Timed Out

        - `5` Failed

        - `6` Ingesting

        - `7` Analyzing

        - `8` Partially Complete

        '
      enum:
      - -1
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    api.params.query.limit:
      type: integer
      minimum: 0
      description: The limit of results requested by the client.
    model.components.int64.id:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: This is the unique identifier for this object.
    api.params.predicate.filter.string:
      type: string
      pattern: ^((eq|~eq|neq):)?[^:]+$
      description: 'Filter results by column string value. Valid filter predicates are `eq`, `~eq`, `neq`.

        '
    model.domain-collection-result:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - $ref: '#/components/schemas/model.components.timestamps'
      - type: object
        properties:
          job_id:
            type: integer
            format: int64
          domain_name:
            description: Name of the domain that was enumerated
            type: string
          success:
            description: A boolean value indicating whether the domain enumeration succeeded
            type: boolean
          message:
            description: A status message for a domain enumeration result
            type: string
          user_count:
            description: A count of users enumerated
            type: integer
          group_count:
            description: A count of groups enumerated
            type: integer
          computer_count:
            description: A count of computers enumerated
            type: integer
          gpo_count:
            description: A count of gpos enumerated
            type: integer
          ou_count:
            description: A count of ous enumerated
            type: integer
          container_count:
            description: A count of containers enumerated
            type: integer
          aiaca_count:
            description: A count of aiacas enumerated
            type: integer
          rootca_count:
            description: A count of rootcas enumerated
            type: integer
          enterpriseca_count:
            description: A count of enterprisecas enumerated
            type: integer
          ntauthstore_count:
            description: A count of ntauthstores enumerated
            type: integer
          certtemplate_count:
            description: A count of certtemplates enumerated
            type: integer
          deleted_count:
            description: A count of deleted objects enumerated
            type: integer
    null.string:
      type: object
      properties:
        string:
          type: string
        valid:
          description: Valid is true if `string` is not `null`
          type: boolean
    api.params.query.sort-by:
      type: string
      description: 'Sort by column. Can be used multiple times; prepend a hyphen for descending order.

        See parameter description for details about which columns are sortable.

        '
    api.error-detail:
      type: object
      properties:
        context:
          type: string
          description: The context in which the error took place
        message:
          type: string
          description: A human-readable description of the error
    null.time:
      type: object
      properties:
        time:
          type: string
          format: date-time
          description: An RFC-3339 formatted string
        valid:
          description: Valid is true if `time` is not `null`.
          type: boolean
    null.int32:
      type: object
      properties:
        int32:
          type: integer
          format: int32
        valid:
          description: Valid is true if `int32` is not `null`.
          type: boolean
    model.client-scheduled-job-display:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - type: object
        properties:
          client_id:
            type: string
            format: uuid
          client_name:
            type: string
          event_id:
            $ref: '#/components/schemas/null.int32'
          execution_time:
            type: string
            format: date-time
          start_time:
            type: string
            format: date-time
          end_time:
            type: string
            format: date-time
          status:
            $ref: '#/components/schemas/enum.job-status'
          status_message:
            type: string
          session_collection:
            type: boolean
          local_group_collection:
            type: boolean
          ad_structure_collection:
            type: boolean
          cert_services_collection:
            type: boolean
          ca_registry_collection:
            type: boolean
          dc_registry_collection:
            type: boolean
          all_trusted_domains:
            type: boolean
          domain_controller:
            type: string
          ous:
            type: array
            items:
              $ref: '#/components/schemas/model.ou-details'
          domains:
            type: array
            items:
              $ref: '#/components/schemas/model.domain-details'
          domain_results:
            type: array
            items:
              $ref: '#/components/schemas/model.domain-collection-result'
    api.error-wrapper:
      type: object
      description: ''
      properties:
        http_status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 600
        timestamp:
          type: string
          format: date-time
          description: The RFC-3339 timestamp in which the error response was sent
        request_id:
          type: string
          format: uuid
          description: The unique identifier of the request that failed
        errors:
          type: array
          items:
            $ref: '#/components/schemas/api.error-detail'
          description: The error(s) that occurred from processing the request
    model.components.timestamps:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/null.time'
    model.domain-details:
      allOf:
      - $ref: '#/components/schemas/model.components.base-ad-entity'
      - type: object
        properties:
          type:
            type: string
    model.ou-details:
      allOf:
      - $ref: '#/components/schemas/model.components.base-ad-entity'
      - type: object
        properties:
          distinguishedname:
            type: string
            nullable: true
          type:
            type: string
            nullable: true
    model.components.base-ad-entity:
      type: object
      properties:
        objectid:
          type: string
        name:
          type: string
          nullable: true
        exists:
          type: boolean
          nullable: true
    api.params.predicate.filter.uuid:
      type: string
      pattern: ^((eq|neq):)?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$
      description: 'Filter results by column string-formatted uuid value. Valid filter predicates are `eq`, `neq`.

        '
    api.params.query.skip:
      type: integer
      minimum: 0
      description: The number of items to skip in a paginated response.
  parameters:
    query.clients.job.session-collection:
      name: session_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.created-at:
      name: created_at
      in: query
      description: Filter results by `created_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.status:
      name: status
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    header.prefer:
      name: Prefer
      description: Prefer header, used to specify a custom timeout in seconds using the wait parameter as per RFC7240. Passing in wait=-1 bypasses all timeout limits when the feature is enabled.
      in: header
      required: false
      schema:
        type: string
        default: wait=30
        pattern: ^wait=(-1|[0-9]+)$
    query.clients.job.start-time:
      name: start_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.execution-time:
      name: execution_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.hydrate-ous:
      name: hydrate_ous
      description: When a value of `true` is passed, any OUs associated with scheduled and finished jobs for each client will have expanded properties including `name` and `type`. When a value of `false` is passed, these same OUs will only return as a list of `objectid`s.
      in: query
      schema:
        type: boolean
        default: true
    query.skip:
      name: skip
      description: This query parameter is used for determining the number of objects to skip in pagination.
      in: query
      schema:
        $ref: '#/components/schemas/api.params.query.skip'
    query.clients.job.domain-controller:
      name: domain_controller
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.clients.job.event-title:
      name: event_title
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.clients.job.end-time:
      name: end_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.updated-at:
      name: updated_at
      in: query
      description: Filter results by `updated_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.event-id:
      name: event_id
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.integer'
    query.clients.job.last-ingest:
      name: last_ingest
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.local-group-collection:
      name: local_group_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.ca-registry-collection:
      name: ca_registry_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.cert-services-collection:
      name: cert_services_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.hydrate-domains:
      name: hydrate_domains
      description: When a value of `true` is passed, any Domains associated with scheduled and finished jobs for each client will have expanded properties including `name` and `type`. When a value of `false` is passed, these same Domains will only return as a list of `objectid`s.
      in: query
      schema:
        type: boolean
        default: true
    query.deleted-at:
      name: deleted_at
      in: query
      description: Filter results by `deleted_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.limit:
      name: limit
      description: This query parameter is used for setting an upper limit of objects returned in paginated responses.
      in: query
      schema:
        $ref: '#/components/schemas/api.params.query.limit'
    query.clients.job.client-id:
      name: client_id
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.uuid'
    query.clients.job.dc-registry-collection:
      name: dc_registry_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.ad-structure-collection:
      name: ad_structure_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.log-path:
      name: log_path
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
  responses:
    not-found:
      description: '**Not Found**

        This error typically comes from operations where a valid ID was passed to the request

        to look up an entity but the entity could not be found.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 404
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The requested client could not be found.
    bad-request:
      description: '**Bad Request**

        This could be due to one of the following reasons:

        - JSON payload is missing or malformed

        - Path or query parameters are missing or invalid/malformed

        - The data sent is not valid (ex- sending a `string` in an `integer` field)

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 400
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The JSON payload could not be unmarshalled.
    forbidden:
      description: '**Forbidden**

        This is most commonly caused by an authenticated client trying to

        access a resource that it does not have permission for.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 403
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: You do not have permission to access this resource
    too-many-requests:
      description: '**Too Many Requests**

        The client has sent too many requests within a certain time window

        and tripped the rate limiting middleware.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 429
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: middleware
              message: Too many requests. Please try again later.
    internal-server-error:
      description: '**Internal Server Error**

        This is usually the result of either an unexpected database or application error.

        The client may try modifying or resending the request, but the error is likely not related to the client

        doing something wrong.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 500
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The request could not be handled due to an unexpected database error.
    unauthorized:
      description: '**Unauthorized**

        This endpoint failed an authentication requirement. Either the client tried to access

        a protected endpoint without being authenticated, or an auth validation failed (ex- invalid

        credentials or expired token).

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 401
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: login
              message: Unauthorized
  securitySchemes:
    JWTBearerToken:
      description: '`Authorization: Bearer $JWT_TOKEN`

        '
      type: http
      scheme: bearer
      bearerFormat: JWT
    SignedRequest:
      description: '`Authorization: bhesignature $TOKEN_ID`

        '
      type: apiKey
      name: Authorization
      in: header
    RequestDate:
      description: '`RequestDate: $RFC3339_DATETIME`

        '
      type: apiKey
      name: RequestDate
      in: header
    HMACSignature:
      description: '`Signature: $BASE64ENCODED_HMAC_SIGNATURE`

        '
      type: apiKey
      name: Signature
      in: header
x-tagGroups:
- name: Community & Enterprise
  tags:
  - Auth
  - Roles
  - Permissions
  - API Tokens
  - BloodHound Users
  - Collectors
  - Collection Uploads
  - Custom Node Management
  - API Info
  - Search
  - Audit
  - Config
  - Asset Isolation
  - Graph
  - Azure Entities
  - AD Base Entities
  - Computers
  - Containers
  - Domains
  - GPOs
  - AIA CAs
  - Root CAs
  - Enterprise CAs
  - NT Auth Stores
  - Cert Templates
  - OUs
  - AD Users
  - Groups
  - Data Quality
  - Datapipe
  - Cypher
  - OpenGraph (Experimental)
- name: Enterprise Only
  tags:
  - EULA
  - BHE Users
  - Analysis
  - Client Ingest
  - Clients
  - Jobs
  - Tasks
  - Events (Schedules)
  - Attack Paths
  - Risk Posture
  - Meta Entities
  - Alerts
