openapi: 3.2.0
info:
  title: BloodHound Jobs API
  contact:
    name: BloodHound Enterprise Support
    url: https://bloodhound.specterops.io/
    email: support@specterops.io
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v2
  description: This is the API that drives BloodHound Enterprise and Community Edition.
servers:
- url: /
  description: This is the base path for all endpoints, relative to the domain where the API is being hosted.
security:
- JWTBearerToken: []
- SignedRequest: []
  RequestDate: []
  HMACSignature: []
tags:
- name: Jobs
paths:
  /api/v2/jobs/available:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: ListAvailableClientJobs
      summary: List available client jobs
      description: 'Endpoint for clients to get next available jobs.


        Note: caller must be a client. For users, this endpoint will return a 404 as

        they are not expected or allowed to call this endpoint.'
      tags:
      - Jobs
      parameters:
      - name: sort_by
        description: Sortable columns are `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, and `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.clients.hydrate-ous'
      - $ref: '#/components/parameters/query.clients.hydrate-domains'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/finished:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: ListClientFinishedJobs
      summary: List finished jobs
      description: Gets all finished jobs
      tags:
      - Jobs
      parameters:
      - name: sort_by
        description: Sortable columns are `client_name`, `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.clients.hydrate-domains'
      - $ref: '#/components/parameters/query.clients.hydrate-ous'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      - $ref: '#/components/parameters/query.skip'
      - $ref: '#/components/parameters/query.limit'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/api.response.pagination'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetClientJobs
      summary: Get jobs
      description: Gets client jobs
      tags:
      - Jobs
      parameters:
      - name: sort_by
        description: Sortable columns are `client_name`, `event_id`, `execution_time`, `status`, `start_time`, `end_time`, `log_path`, `domain_controller`, `event_title`, `last_ingest`, `id`, `created_at`, `updated_at`, `deleted_at`.
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.sort-by'
      - $ref: '#/components/parameters/query.clients.job.log-path'
      - $ref: '#/components/parameters/query.clients.job.session-collection'
      - $ref: '#/components/parameters/query.clients.job.local-group-collection'
      - $ref: '#/components/parameters/query.clients.job.cert-services-collection'
      - $ref: '#/components/parameters/query.clients.job.ca-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.dc-registry-collection'
      - $ref: '#/components/parameters/query.clients.job.ad-structure-collection'
      - $ref: '#/components/parameters/query.clients.job.domain-controller'
      - $ref: '#/components/parameters/query.clients.job.status'
      - $ref: '#/components/parameters/query.clients.job.event-title'
      - $ref: '#/components/parameters/query.clients.job.client-id'
      - $ref: '#/components/parameters/query.clients.job.event-id'
      - $ref: '#/components/parameters/query.clients.job.execution-time'
      - $ref: '#/components/parameters/query.clients.job.start-time'
      - $ref: '#/components/parameters/query.clients.job.end-time'
      - $ref: '#/components/parameters/query.clients.job.last-ingest'
      - $ref: '#/components/parameters/query.created-at'
      - $ref: '#/components/parameters/query.updated-at'
      - $ref: '#/components/parameters/query.deleted-at'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/current:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    get:
      operationId: GetClientCurrentJob
      summary: Get client current job
      description: 'Gets the current job for the authenticated client.


        Note: caller must be a client. For users, this endpoint will return a 404 as

        they are not expected or allowed to call this endpoint.'
      tags:
      - Jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/start:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    post:
      operationId: StartClientJob
      summary: Notifies the API of a job start
      description: 'Endpoint for clients to start a new job and mark the start time.


        Note: caller must be a client. For users, this endpoint will return a 404 as

        they are not expected or allowed to call this endpoint.'
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/end:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    post:
      operationId: EndClientJob
      summary: Notifies the API of a job ending
      description: 'Endpoint for clients to end a job and mark the end time.


        Note: caller must be a client. For users, this endpoint will return a 404 as

        they are not expected or allowed to call this endpoint.'
      tags:
      - Jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/{job_id}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: job_id
      description: Job ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    get:
      operationId: GetClientJob
      summary: Get client job
      description: Gets client job
      tags:
      - Jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/{job_id}/cancel:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: job_id
      description: Job ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    put:
      operationId: CancelClientJob
      summary: Cancels a scheduled job
      tags:
      - Jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/model.client-scheduled-job-display'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
  /api/v2/jobs/{job_id}/log:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: job_id
      description: Job ID
      in: path
      required: true
      schema:
        type: integer
        format: int64
    get:
      operationId: GetClientJobLog
      summary: Get Job Log File
      description: Get the log file from a SharpHound run
      tags:
      - Jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      log:
                        type: string
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
components:
  responses:
    forbidden:
      description: '**Forbidden**

        This is most commonly caused by an authenticated client trying to

        access a resource that it does not have permission for.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 403
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: You do not have permission to access this resource
    internal-server-error:
      description: '**Internal Server Error**

        This is usually the result of either an unexpected database or application error.

        The client may try modifying or resending the request, but the error is likely not related to the client

        doing something wrong.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 500
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The request could not be handled due to an unexpected database error.
    unauthorized:
      description: '**Unauthorized**

        This endpoint failed an authentication requirement. Either the client tried to access

        a protected endpoint without being authenticated, or an auth validation failed (ex- invalid

        credentials or expired token).

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 401
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: login
              message: Unauthorized
    too-many-requests:
      description: '**Too Many Requests**

        The client has sent too many requests within a certain time window

        and tripped the rate limiting middleware.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 429
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: middleware
              message: Too many requests. Please try again later.
    not-found:
      description: '**Not Found**

        This error typically comes from operations where a valid ID was passed to the request

        to look up an entity but the entity could not be found.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 404
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The requested client could not be found.
    bad-request:
      description: '**Bad Request**

        This could be due to one of the following reasons:

        - JSON payload is missing or malformed

        - Path or query parameters are missing or invalid/malformed

        - The data sent is not valid (ex- sending a `string` in an `integer` field)

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 400
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The JSON payload could not be unmarshalled.
  schemas:
    api.params.query.limit:
      type: integer
      minimum: 0
      description: The limit of results requested by the client.
    model.client-scheduled-job-display:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - type: object
        properties:
          client_id:
            type: string
            format: uuid
          client_name:
            type: string
          event_id:
            $ref: '#/components/schemas/null.int32'
          execution_time:
            type: string
            format: date-time
          start_time:
            type: string
            format: date-time
          end_time:
            type: string
            format: date-time
          status:
            $ref: '#/components/schemas/enum.job-status'
          status_message:
            type: string
          session_collection:
            type: boolean
          local_group_collection:
            type: boolean
          ad_structure_collection:
            type: boolean
          cert_services_collection:
            type: boolean
          ca_registry_collection:
            type: boolean
          dc_registry_collection:
            type: boolean
          all_trusted_domains:
            type: boolean
          domain_controller:
            type: string
          ous:
            type: array
            items:
              $ref: '#/components/schemas/model.ou-details'
          domains:
            type: array
            items:
              $ref: '#/components/schemas/model.domain-details'
          domain_results:
            type: array
            items:
              $ref: '#/components/schemas/model.domain-collection-result'
    api.params.predicate.filter.integer:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?-?[0-9]+$
      description: 'Filter results by column integer value. Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    model.client-scheduled-job:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - $ref: '#/components/schemas/model.components.timestamps'
      - type: object
        properties:
          client_id:
            type: string
            format: uuid
            readOnly: true
          client_name:
            type: string
            readOnly: true
          event_id:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/null.int32'
          status:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/enum.job-status'
          statusMessage:
            type: string
            readOnly: true
          start_time:
            type: string
            format: date-time
            readOnly: true
          end_time:
            type: string
            format: date-time
            readOnly: true
          log_path:
            readOnly: true
            allOf:
            - $ref: '#/components/schemas/null.string'
          session_collection:
            type: boolean
          local_group_collection:
            type: boolean
          ad_structure_collection:
            type: boolean
          cert_services_collection:
            type: boolean
          ca_registry_collection:
            type: boolean
          dc_registry_collection:
            type: boolean
          all_trusted_domains:
            type: boolean
          domain_controller:
            $ref: '#/components/schemas/null.string'
          event_title:
            type: string
            readOnly: true
          last_ingest:
            type: string
            format: date-time
            readOnly: true
          ous:
            type: array
            readOnly: true
            items:
              type: string
          domains:
            type: array
            readOnly: true
            items:
              type: string
          domain_results:
            type: array
            readOnly: true
            items:
              $ref: '#/components/schemas/model.domain-collection-result'
    null.time:
      type: object
      properties:
        time:
          type: string
          format: date-time
          description: An RFC-3339 formatted string
        valid:
          description: Valid is true if `time` is not `null`.
          type: boolean
    api.error-detail:
      type: object
      properties:
        context:
          type: string
          description: The context in which the error took place
        message:
          type: string
          description: A human-readable description of the error
    api.params.query.sort-by:
      type: string
      description: 'Sort by column. Can be used multiple times; prepend a hyphen for descending order.

        See parameter description for details about which columns are sortable.

        '
    model.components.timestamps:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/null.time'
    null.int32:
      type: object
      properties:
        int32:
          type: integer
          format: int32
        valid:
          description: Valid is true if `int32` is not `null`.
          type: boolean
    model.domain-collection-result:
      allOf:
      - $ref: '#/components/schemas/model.components.int64.id'
      - $ref: '#/components/schemas/model.components.timestamps'
      - type: object
        properties:
          job_id:
            type: integer
            format: int64
          domain_name:
            description: Name of the domain that was enumerated
            type: string
          success:
            description: A boolean value indicating whether the domain enumeration succeeded
            type: boolean
          message:
            description: A status message for a domain enumeration result
            type: string
          user_count:
            description: A count of users enumerated
            type: integer
          group_count:
            description: A count of groups enumerated
            type: integer
          computer_count:
            description: A count of computers enumerated
            type: integer
          gpo_count:
            description: A count of gpos enumerated
            type: integer
          ou_count:
            description: A count of ous enumerated
            type: integer
          container_count:
            description: A count of containers enumerated
            type: integer
          aiaca_count:
            description: A count of aiacas enumerated
            type: integer
          rootca_count:
            description: A count of rootcas enumerated
            type: integer
          enterpriseca_count:
            description: A count of enterprisecas enumerated
            type: integer
          ntauthstore_count:
            description: A count of ntauthstores enumerated
            type: integer
          certtemplate_count:
            description: A count of certtemplates enumerated
            type: integer
          deleted_count:
            description: A count of deleted objects enumerated
            type: integer
    model.domain-details:
      allOf:
      - $ref: '#/components/schemas/model.components.base-ad-entity'
      - type: object
        properties:
          type:
            type: string
    model.components.int64.id:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: This is the unique identifier for this object.
    enum.job-status:
      type: integer
      description: 'This enum describes the current status of a Job. Values are:

        - `-1` Invalid

        - `0` Ready

        - `1` Running

        - `2` Complete

        - `3` Canceled

        - `4` Timed Out

        - `5` Failed

        - `6` Ingesting

        - `7` Analyzing

        - `8` Partially Complete

        '
      enum:
      - -1
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    api.params.predicate.filter.string:
      type: string
      pattern: ^((eq|~eq|neq):)?[^:]+$
      description: 'Filter results by column string value. Valid filter predicates are `eq`, `~eq`, `neq`.

        '
    api.params.predicate.filter.time:
      type: string
      pattern: ^((eq|neq|gt|gte|lt|lte):)?[0-9]{4}-[0-9]{2}-[0-9]{2}[Tt][0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,9})?([Zz]|-[0-9]{2}:[0-9]{2})$
      description: 'Filter results by column timestamp value formatted as an RFC-3339 string.

        Valid filter predicates are `eq`, `neq`, `gt`, `gte`, `lt`, `lte`.

        '
    model.ou-details:
      allOf:
      - $ref: '#/components/schemas/model.components.base-ad-entity'
      - type: object
        properties:
          distinguishedname:
            type:
            - string
            - 'null'
          type:
            type:
            - string
            - 'null'
    api.response.pagination:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          description: The total number of results.
        skip:
          $ref: '#/components/schemas/api.params.query.skip'
        limit:
          $ref: '#/components/schemas/api.params.query.limit'
    api.params.query.skip:
      type: integer
      minimum: 0
      description: The number of items to skip in a paginated response.
    model.components.base-ad-entity:
      type: object
      properties:
        objectid:
          type: string
        name:
          type:
          - string
          - 'null'
        exists:
          type:
          - boolean
          - 'null'
    api.error-wrapper:
      type: object
      description: ''
      properties:
        http_status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 600
        timestamp:
          type: string
          format: date-time
          description: The RFC-3339 timestamp in which the error response was sent
        request_id:
          type: string
          format: uuid
          description: The unique identifier of the request that failed
        errors:
          type: array
          items:
            $ref: '#/components/schemas/api.error-detail'
          description: The error(s) that occurred from processing the request
    null.string:
      type: object
      properties:
        string:
          type: string
        valid:
          description: Valid is true if `string` is not `null`
          type: boolean
    api.params.predicate.filter.boolean:
      type: string
      pattern: ^((eq|neq):)?(t|T|TRUE|true|True|f|F|FALSE|false|False)$
      description: 'Filter results by column boolean value. Valid filter predicates are `eq`, `neq`.

        '
    api.params.predicate.filter.uuid:
      type: string
      pattern: ^((eq|neq):)?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$
      description: 'Filter results by column string-formatted uuid value. Valid filter predicates are `eq`, `neq`.

        '
  parameters:
    query.clients.job.ca-registry-collection:
      name: ca_registry_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.updated-at:
      name: updated_at
      in: query
      description: Filter results by `updated_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.execution-time:
      name: execution_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.start-time:
      name: start_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.event-title:
      name: event_title
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.clients.job.client-id:
      name: client_id
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.uuid'
    query.clients.job.status:
      name: status
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.created-at:
      name: created_at
      in: query
      description: Filter results by `created_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.end-time:
      name: end_time
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.log-path:
      name: log_path
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.clients.job.event-id:
      name: event_id
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.integer'
    query.limit:
      name: limit
      description: This query parameter is used for setting an upper limit of objects returned in paginated responses.
      in: query
      schema:
        $ref: '#/components/schemas/api.params.query.limit'
    query.clients.job.ad-structure-collection:
      name: ad_structure_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.last-ingest:
      name: last_ingest
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.hydrate-ous:
      name: hydrate_ous
      description: When a value of `true` is passed, any OUs associated with scheduled and finished jobs for each client will have expanded properties including `name` and `type`. When a value of `false` is passed, these same OUs will only return as a list of `objectid`s.
      in: query
      schema:
        type: boolean
        default: true
    query.skip:
      name: skip
      description: This query parameter is used for determining the number of objects to skip in pagination.
      in: query
      schema:
        $ref: '#/components/schemas/api.params.query.skip'
    query.clients.job.domain-controller:
      name: domain_controller
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.string'
    query.deleted-at:
      name: deleted_at
      in: query
      description: Filter results by `deleted_at` value. See filter schema details for valid predicates.
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.time'
    query.clients.job.dc-registry-collection:
      name: dc_registry_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.hydrate-domains:
      name: hydrate_domains
      description: When a value of `true` is passed, any Domains associated with scheduled and finished jobs for each client will have expanded properties including `name` and `type`. When a value of `false` is passed, these same Domains will only return as a list of `objectid`s.
      in: query
      schema:
        type: boolean
        default: true
    query.clients.job.cert-services-collection:
      name: cert_services_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    header.prefer:
      name: Prefer
      description: Prefer header, used to specify a custom timeout in seconds using the wait parameter as per RFC7240. Passing in wait=-1 bypasses all timeout limits when the feature is enabled.
      in: header
      required: false
      schema:
        type: string
        default: wait=30
        pattern: ^wait=(-1|[0-9]+)$
    query.clients.job.session-collection:
      name: session_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
    query.clients.job.local-group-collection:
      name: local_group_collection
      in: query
      schema:
        $ref: '#/components/schemas/api.params.predicate.filter.boolean'
  securitySchemes:
    JWTBearerToken:
      description: '`Authorization: Bearer $JWT_TOKEN`

        '
      type: http
      scheme: bearer
      bearerFormat: JWT
    SignedRequest:
      description: '`Authorization: bhesignature $TOKEN_ID`

        '
      type: apiKey
      name: Authorization
      in: header
    RequestDate:
      description: '`RequestDate: $RFC3339_DATETIME`

        '
      type: apiKey
      name: RequestDate
      in: header
    HMACSignature:
      description: '`Signature: $BASE64ENCODED_HMAC_SIGNATURE`

        '
      type: apiKey
      name: Signature
      in: header
x-tagGroups:
- name: Community & Enterprise
  tags:
  - Auth
  - Roles
  - Permissions
  - API Tokens
  - BloodHound Users
  - Collectors
  - Collection Uploads
  - Custom Node Management
  - API Info
  - Search
  - Audit
  - Config
  - Asset Isolation
  - Graph
  - Azure Entities
  - AD Base Entities
  - Computers
  - Containers
  - Domains
  - GPOs
  - AIA CAs
  - Root CAs
  - Enterprise CAs
  - NT Auth Stores
  - Cert Templates
  - OUs
  - AD Users
  - Groups
  - Data Quality
  - Datapipe
  - Cypher
  - OpenGraph (Experimental)
- name: Enterprise Only
  tags:
  - EULA
  - BHE Users
  - Analysis
  - Client Ingest
  - Clients
  - Jobs
  - Tasks
  - Events (Schedules)
  - Attack Paths
  - Risk Posture
  - Meta Entities
  - Alerts
